
import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { ThemeProvider } from '@/components/ThemeProvider';

//components
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Nicolas Rojas',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
 
      <body className={inter.className} suppressHydrationWarning >
        <ThemeProvider attribute='class' defaultTheme='light'>
          <Header/>
          {children}
          <Footer/>
        </ThemeProvider>
      </body>
 
    </html>
  )
}
